version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - MONGODB_URI=mongodb+srv://jerryxu2487826822:9TJEFlFrrvtMa9jn@cluster0.6f4w2f5.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    volumes:
      - ./public:/usr/src/app/public
    restart: unless-stopped 